### ISSUE TITLE
Doesn't have all the dependencies needed to run the project.

### ISSUE THREAD

**Issue by kartikcho** [shubhamgoel2525/ReactWeather#2]
Other than node_modules (ignored due to size of the folder), specific dependencies like fonts, glyphicons, bootstrap etc. are not included.

### To fix, you could...
* Add CDNs
* Upload the dependencies in the repo

**Comment by abhishekashyap** [comment]
Use **npm install** to get all the dependencies.
Fonts are used via CDN
